version: '3.3'
services:
   postgres:
      container_name: postgres
      image: postgres:14.0-alpine
      restart: unless-stopped
      environment:
         - /var/lib/hydrominder/var/db.env
   api:
      container_name: api
      image: registry.gitlab.utwente.nl/cs21-32/hydrominder_api
      command: bash -c "docker login registry.gitlab.utwente.nl -u CLIENT -p AZuNxneL16MhQ2xsxDBv"
      restart: unless-stopped
      environment:
         - /var/lib/hydrominder/var/db.env
         - /var/lib/hydrominder/var/api.env
      ports:
         - 3000:3000
      depends_on:
         - postgres
