version: '3.3'
services:
   postgres:
      container_name: postgres
      image: postgres:14.0-alpine
      restart: unless-stopped
      env_file:
         - ../var/db.env
   api:
      container_name: api
      image: registry.gitlab.utwente.nl/cs21-32/hydrominder_api
      restart: unless-stopped
      env_file:
         - ../var/db.env
         - ../var/api.env
         - ../var/api_cookie.env
         - ../var/controller_token.env:
      volumes:
         - ../shutdown_signal:/shutdown_signal
      depends_on:
         - postgres
   webapp:
      container_name: webapp
      image: registry.gitlab.utwente.nl/cs21-32/hydrominder_app
      restart: unless-stopped
      env_file:
         - ../var/webapp.env
      ports:
         - 80:80
         - 443:443
      depends_on:
         - api
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
         - ../ssl/hydrominder.crt:/etc/ssl/certs/hydrominder-selfsigned.crt:ro
         - ../ssl/hydrominder.key:/etc/ssl/private/hydrominder-selfsigned.key:ro
