version: '3.3'
services:
   postgres:
      container_name: postgres
      image: postgres:14.0-alpine
      restart: unless-stopped
      env_file:
         - /var/lib/hydrominder/var/db.env
   api:
      container_name: api
      image: registry.gitlab.utwente.nl/cs21-32/hydrominder_api
      restart: unless-stopped
      env_file:
         - /var/lib/hydrominder/var/db.env
         - /var/lib/hydrominder/var/api.env
         - /var/lib/hydrominder/var/api_cookie.env
         - /var/lib/hydrominder/var/controller_token.env
      volumes:
         - /var/lib/hydrominder/shutdown_signal:/shutdown_signal
      depends_on:
         - postgres
