version: '3.7'
services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'hydrominder'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
